
// Mock data for the application

// Courses
export const mockCourses = [
  {
    id: '1',
    title: 'Introduction to Computer Science',
    instructor: 'Dr. Ramesh Kumar',
    subject: 'Computer Science',
    color: '#4285F4',
    pendingAssignments: 2,
  },
  {
    id: '2',
    title: 'Business Administration',
    instructor: 'Prof. Sanjay Patel',
    subject: 'Management',
    color: '#0F9D58',
    pendingAssignments: 0,
  },
  {
    id: '3',
    title: 'Financial Accounting',
    instructor: 'Dr. Priya Sharma',
    subject: 'Accounting',
    color: '#DB4437',
    pendingAssignments: 1,
  },
  {
    id: '4',
    title: 'Marketing Management',
    instructor: 'Prof. Anjali Gupta',
    subject: 'Marketing',
    color: '#F4B400',
    pendingAssignments: 1,
  },
  {
    id: '5',
    title: 'Business Law',
    instructor: 'Dr. Arjun Reddy',
    subject: 'Law',
    color: '#673AB7',
    pendingAssignments: 0,
  },
  {
    id: '6',
    title: 'Business Ethics',
    instructor: 'Prof. Meera Desai',
    subject: 'Ethics',
    color: '#FF6D00',
    pendingAssignments: 1,
  },
];

// Students
export const mockStudents = [
  {
    id: '1',
    name: 'Rahul Sharma',
    rollNumber: 'BBA2021001',
    course: 'Business Administration',
    semester: 3,
    attendance: 92,
    behaviorScore: 90,
    academicScore: 88,
    avatar: 'https://i.pravatar.cc/150?u=1',
    behavioralIncidents: [],
  },
  {
    id: '2',
    name: 'Priya Patel',
    rollNumber: 'BBA2021002',
    course: 'Business Administration',
    semester: 3,
    attendance: 65,
    behaviorScore: 75,
    academicScore: 82,
    avatar: 'https://i.pravatar.cc/150?u=2',
    behavioralIncidents: [
      {
        type: 'Disruptive Behavior',
        description: 'Talking excessively during lecture despite warnings.',
        date: '2023-09-05',
      },
    ],
  },
  {
    id: '3',
    name: 'Amit Kumar',
    rollNumber: 'BCA2021001',
    course: 'Computer Applications',
    semester: 3,
    attendance: 85,
    behaviorScore: 95,
    academicScore: 92,
    avatar: 'https://i.pravatar.cc/150?u=3',
    behavioralIncidents: [],
  },
  {
    id: '4',
    name: 'Neha Gupta',
    rollNumber: 'BCA2021002',
    course: 'Computer Applications',
    semester: 3,
    attendance: 78,
    behaviorScore: 88,
    academicScore: 86,
    avatar: 'https://i.pravatar.cc/150?u=4',
    behavioralIncidents: [],
  },
  {
    id: '5',
    name: 'Rajesh Singh',
    rollNumber: 'BCom2021001',
    course: 'Commerce',
    semester: 3,
    attendance: 60,
    behaviorScore: 65,
    academicScore: 72,
    avatar: 'https://i.pravatar.cc/150?u=5',
    behavioralIncidents: [
      {
        type: 'Academic Dishonesty',
        description: 'Suspected of cheating during mid-term exam.',
        date: '2023-08-17',
      },
      {
        type: 'Attendance Issue',
        description: 'Consistently arriving late to morning classes.',
        date: '2023-09-10',
      },
    ],
  },
  {
    id: '6',
    name: 'Anjali Desai',
    rollNumber: 'BCom2021002',
    course: 'Commerce',
    semester: 3,
    attendance: 90,
    behaviorScore: 92,
    academicScore: 90,
    avatar: 'https://i.pravatar.cc/150?u=6',
    behavioralIncidents: [],
  },
  {
    id: '7',
    name: 'Vikram Mehta',
    rollNumber: 'BHM2021001',
    course: 'Hotel Management',
    semester: 3,
    attendance: 72,
    behaviorScore: 85,
    academicScore: 78,
    avatar: 'https://i.pravatar.cc/150?u=7',
    behavioralIncidents: [],
  },
  {
    id: '8',
    name: 'Pooja Verma',
    rollNumber: 'BHM2021002',
    course: 'Hotel Management',
    semester: 3,
    attendance: 95,
    behaviorScore: 90,
    academicScore: 91,
    avatar: 'https://i.pravatar.cc/150?u=8',
    behavioralIncidents: [],
  },
];

// Teachers
export const mockTeachers = [
  {
    id: '1',
    name: 'Dr. Ramesh Kumar',
    department: 'Computer Science',
    subject: 'Programming',
    email: 'ramesh.kumar@asbm.edu',
    avatar: 'https://i.pravatar.cc/150?u=t1',
  },
  {
    id: '2',
    name: 'Prof. Sanjay Patel',
    department: 'Business Administration',
    subject: 'Management',
    email: 'sanjay.patel@asbm.edu',
    avatar: 'https://i.pravatar.cc/150?u=t2',
  },
  {
    id: '3',
    name: 'Dr. Priya Sharma',
    department: 'Commerce',
    subject: 'Accounting',
    email: 'priya.sharma@asbm.edu',
    avatar: 'https://i.pravatar.cc/150?u=t3',
  },
  {
    id: '4',
    name: 'Prof. Anjali Gupta',
    department: 'Marketing',
    subject: 'Digital Marketing',
    email: 'anjali.gupta@asbm.edu',
    avatar: 'https://i.pravatar.cc/150?u=t4',
  },
  {
    id: '5',
    name: 'Dr. Arjun Reddy',
    department: 'Law',
    subject: 'Business Law',
    email: 'arjun.reddy@asbm.edu',
    avatar: 'https://i.pravatar.cc/150?u=t5',
  },
  {
    id: '6',
    name: 'Prof. Meera Desai',
    department: 'Philosophy',
    subject: 'Ethics',
    email: 'meera.desai@asbm.edu',
    avatar: 'https://i.pravatar.cc/150?u=t6',
  },
  {
    id: '7',
    name: 'Dr. Rajiv Malhotra',
    department: 'Economics',
    subject: 'Microeconomics',
    email: 'rajiv.malhotra@asbm.edu',
    avatar: 'https://i.pravatar.cc/150?u=t7',
  },
  {
    id: '8',
    name: 'Prof. Shikha Puri',
    department: 'Statistics',
    subject: 'Business Statistics',
    email: 'shikha.puri@asbm.edu',
    avatar: 'https://i.pravatar.cc/150?u=t8',
  },
];
